### PR TITLE
fix systemd collector dbus connection

### PR DESCRIPTION
**Pull request by kopiczko**
Towards https://github.com/giantswarm/giantswarm/issues/6178.

Reverts changes introduced with https://github.com/giantswarm/kubernetes-node-exporter/pull/39. After fixing some immediate problems with mounts node-exporter pods fail with:

```
couldn't get units: couldn't get dbus connection: dbus: authentication failed
```

Here's a related issue https://github.com/prometheus/node_exporter/issues/1290.

We need those guys back in the node-exporter DS in order to make things
work again:

```
      securityContext:
          privileged: true
```

```
      securityContext:
        runAsUser: 0
```

That won't work with the introduced PSP hardening. It's reverted to this
working version:
https://github.com/giantswarm/kubernetes-node-exporter/blob/4097ca02ef4abff81021126629b4a7768cd7764a/helm/kubernetes-node-exporter-chart/templates/psp.yaml

### CODE REVIEW

**Review by pipo02mix — APPROVED** [review]
LGTM but I would wait for VOl feedback

**Review by TheoBrigitte — APPROVED** [review]
This was successfully deployed and tested on a TC

release 8.2.0
channel wip-1397203aabc5db86a3cdfc6ac5000626929fde0d

Running since 15mn, manually scraped the /metrics endpoint, no errors in logs.

**Comment by corest** [comment]
I see in original issue it was fixed by running container with the same user we have on host system. Why don’t you try that instead of reverting to root?

**Comment by corest** [comment]
Here is the basic `Dockerfile`:
```
FROM quay.io/giantswarm/node-exporter:v0.18.0

USER root
RUN addgroup -g 1000 -S giantswarm && adduser -u 1000 -S giantswarm -G giantswarm
USER giantswarm
```

With this I've changed `runAsUser` to `1000` (that is the `giantswarm` user we have on host as well).

And that's the way you can automate rebuilding of the image with additional user

https://github.com/giantswarm/retagger/blob/master/images.yaml#L5-L9
 
I've run that for 30min, didn't get any errors

**Comment by kopiczko** [comment]
Closing in favour of https://github.com/giantswarm/kubernetes-node-exporter/pull/44.

**Pull request closed without merging**
