### PR TITLE
Integrate helm chart testing into circleci

### PR DESCRIPTION
**Pull request by indyfree**
Towards https://github.com/giantswarm/giantswarm/issues/1902, https://github.com/giantswarm/giantswarm/issues/2706

Test helm charts with `helm test` via `e2e-harness`.

~The release process of charts is not fully in place yet. We currently push and test to/from `stable` channel with every PR. This wil change with future PRs.~

### CODE REVIEW

**Review by MarcelMue — COMMENTED** [review]
This will mainly be questions from my side, I have just recently gotten started with our integration test setup.

**Review by rossf7 — APPROVED** [review]
LGTM. Yes as described in the spec we reconcile against a release channel in CNR. 

The release channel is controlled by the chartconfig CR and is versioned with version bundles.

Maybe not everything is in place you'll need to test. In Quay I don't see any channels for `giantswarm/kubernetes-node-exporter-chart`.

**Review by MarcelMue — APPROVED** [review]
I am fine with this.

**Review by indyfree — COMMENTED** [review]
The chart release process is not fully in place yet. Going to leave this open till `architect publish` works as intended and I find a way to reference the current (not the most recent) chart in testing.

**Review by fgimenez — COMMENTED** [review]
Looks good, I think we can use a channel name specific to the commit, and a single test job for PR and master, let me know WDYT.

**Review by indyfree — COMMENTED** [review]
Add install and Test from temporary `SHA` channel to avoid collisions. Release to `beta` on merge to master. Will add cleanup of `SHA`-channel (unpublish) in a later PR. PTAL :)

**Review by fgimenez — APPROVED** [review]
Very nice! :+1: just one suggestion about a more lightweight setup.

**Pull request merged**
